### Upload Image
### Variables globales
@baseUrl = http://localhost:5000
POST {{baseUrl}}/upload/image
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary
Authorization: Bearer your-token-here

------WebKitFormBoundary
Content-Disposition: form-data; name="email"

raouanedev@gmail.com
------WebKitFormBoundary
Content-Disposition: form-data; name="image"; filename="hero.jpg"
Content-Type: image/jpeg

< c:/Users/raoua/cursorproject/hajj-backend-temp/test-images/hero.jpg
------WebKitFormBoundary--
