### Upload Image
### Variables globales
@baseUrl = https://hajj-omra-booking-backend.onrender.com
POST {{baseUrl}}/upload/image
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary
Authorization: Bearer your-token-here

------WebKitFormBoundary
Content-Disposition: form-data; name="email"

raouanedev@gmail.com
------WebKitFormBoundary
Content-Disposition: form-data; name="image"; filename="hero.jpg"
Content-Type: image/jpeg

< ./test-images/hero.jpg
------WebKitFormBoundary-- 